export const HOMEWORK_REQUEST = "HOMEWORK_RESQUEST"
export const HOMEWORK_SUCCESS = "HOMEWORK_SUCCESS"
export const HOMEWORK_FAILURE = "HOMEWORK_FAILURE"

export const USER_DATA_REQUEST = "USER_DATA_RESQUEST"
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS"
export const USER_DATA_FAILURE = "USER_DATA_FAILURE"
export const GET_USER_ROLE = "GET_USER_ROLE"
